service: dashboard

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  retrieveDashboardData:
    handler: api/dashboard.fetchTopUsageDataAndSendEmail
    memorySize: 256
    description: Retrieve Top Usage Data from API
    events:
      - http:
          method: get
          path: fetchDataAndSendEmail
  verifyEmail:
    handler: api/verifyEmail.handler
    memorySize: 128
    description: Send email to SES and trigger verification process
    events:
      - http:
          method: post
          path: verifyEmail
          cors: true

package:
  individually: true
  exclude:
    - node_modules/**

#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# env variables if needed
#  environment:
#    variable1: value1