service: dashboard

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  retrieveDashboardData:
    handler: api/dashboard.fetchTopUsageData
    memorySize: 256
    description: Retrieve Top Usage Data from API
    events:
      - http: GET fetchTopUsageData
  sendEmail:
    handler: api/sendEmail.handler
    memorySize: 128
    description: Send email containing dashboard data to email address
    events:
      - http:
          method: post
          path: sendEmail
          cors: true
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# env variables if needed
#  environment:
#    variable1: value1