service: dashboard

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  role: clpPrototypeRole

functions:
  retrieveDashboardData:
    handler: api/index.fetchTopUsageDataAndSendEmail
    memorySize: 256
    timeout: 30
    description: Retrieve Top Usage Data from API
    events:
      - http:
          method: get
          path: /fetchDataAndSendEmail
  verifyEmail:
    handler: api/index.verifyEmail
    memorySize: 128
    timeout: 30
    description: Send email to SES and trigger verification process
    events:
      - http:
          method: post
          path: /verifyEmail
          cors: true

resources:
  Resources:
    clpPrototypeRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: clp-prototype-role-dev
        Policies:
          - PolicyName: clp-prototype-fullstack-policy-dev
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:DescribeLogStreams
                    - ses:SendEmail
                    - ses:ListIdentities
                    - ses:GetIdentityVerificationAttributes
                    - ses:VerifyEmailIdentity
                  Resource: "*"
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole