version: 2
jobs:
  unit_test:
    working_directory: /tmp/lambda-email-notified
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          key: node-module-cache-{{ checksum "package.json" }}
      - run: npm install
      - run: npm test
      - save_cache:
          key: node-module-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  build_and_deploy:
    working_directory: /tmp/lambda-email-notified
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          key: node-module-cache-{{ checksum "package.json" }}
      - deploy:
          name: Push application Docker image
          command: |
            npm run deploy

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - unit_test:
          filters:
            tags:
              only: /.*/
      - build_and_deploy:
          requires:
            - unit_test
          filters:
            branches:
              only:
                - develop
                - master
            tags:
              only: /.*/
